server:  
  port: 8090  
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
  
spring.mvc.static-path-pattern: /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#mybatis: 
#  mapperLocations: classpath:com.trs.appserver.model.mapper/*.xml
#  typeAliasesPackage: tk.mapper.model
#spring.datasource:
#  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
#  username: root
#  password: root
#  driver-class-name: com.mysql.jdbc.Driver
#  max-active: 20
#  max-idle: 20
#  min-idle: 0
spring:
    datasource:
        primary:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
            username: root
            password: root